# # This is an example Starter pipeline configuration
# # Use a skeleton to build, test and deploy using manual and parallel steps
# # -----
# # You can specify a custom docker image from Docker Hub as your build environment.

# image: atlassian/default-image:3

# pipelines:
#   default:
#     - parallel:
#       - step:
#           name: 'Build and Test'
#           script:
#             - echo "Your build and test goes here..."
#       - step:
#           name: 'Lint'
#           script:
#             - echo "Your linting goes here..."
#       - step:
#           name: 'Security scan'
#           script:
#             - echo "Your security scan goes here..."

#     # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
#     - step:
#         name: 'Deployment to Staging'
#         deployment: staging
#         script:
#           - echo "Your deployment to staging script goes here..."
#     - step:
#         name: 'Deployment to Production'
#         deployment: production
#         trigger: 'manual'
#         script:
#           - echo "Your deployment to production script goes here..."
# bitbucket-pipelines.yml
 
pipelines:
  branches:
    main:
      - step:
          name: Build and Package
          image: node:18.17.0
          caches:
            - node
          script:
            - echo "Starting the build process"
            - npm ci
            - npm run build
            - echo "Build completed. Checking .next/standalone directory..."
            - ls -l .next
          artifacts:
            - .next/**

      - step: &deploy
          name: Deploy to Production
          deployment: production
          script:
            - echo "Deploying to production"
            - ls -l .next/server/app
            - ls -l .next/server/app/**
            - pipe: atlassian/ftp-deploy:0.3.1
              variables:
                USERNAME: $mindspothealthcare@mindspothealthcare.com
                PASSWORD: $gR1=$Fs3RSB%K_I*^Q
                SERVER: ftp.mindspothealthcare.com
                REMOTE_PATH: /
                LOCAL_PATH: .next/standalone
                MODE: "script"
                COMMAND: "./ansible/deploy-dev.sh"

definitions:
  caches:
    node: ~/.npm
